# Generated by Django 3.2.8 on 2021-10-24 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20211024_1018'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
